# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-06 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('url', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[(b'get', b'get'), (b'post', b'post'), (b'put', b'put'), (b'delete', b'delete')], default=b'get', max_length=20)),
                ('comment', models.TextField(null=True)),
                ('headers', models.CharField(max_length=2000, null=True)),
                ('paramters', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('ver', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('create_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=b'200', max_length=20)),
                ('headers', models.CharField(max_length=2000, null=True)),
                ('data', models.CharField(max_length=2000, null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apidoc_response_set', to='webapi.ApiDoc')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='\u9519\u8bef\u7f16\u7801')),
                ('name', models.CharField(db_index=True, max_length=40, verbose_name='\u9519\u8bef\u540d\u79f0')),
                ('message', models.CharField(max_length=200, null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.ApiDoc')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.Application')),
            ],
        ),
        migrations.AddField(
            model_name='apidoc',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.Module'),
        ),
    ]
